/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    groovy
    `maven-publish`
}

repositories {
    maven(url = "https://maven.aliyun.com/repository/central")
    maven(url = "https://maven.aliyun.com/repository/jcenter")
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.jetbrains:annotations:22.0.0")
    implementation("org.slf4j:slf4j-api:1.7.32")

    implementation("io.netty:netty-buffer:4.1.71.Final")

    implementation("org.codehaus.groovy:groovy-all:3.0.8")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.slf4j:slf4j-simple:1.7.32")
}

group = "io.github.yezhihao"
version = "3.0.0"
description = "Protostar"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
